export type BiomarkerDefinition = {
  key: string;
  label: string;
  units: string[];
  patterns: RegExp[];
  exclude?: RegExp[];
  reference?: string;
  low?: number;
  high?: number;
  borderlineLow?: number;
  borderlineHigh?: number;
  priority: number;
  legacyField?:
    | "hemoglobin_a1c"
    | "fasting_glucose"
    | "total_cholesterol"
    | "ldl"
    | "hdl"
    | "triglycerides"
    | "hemoglobin"
    | "wbc"
    | "platelets"
    | "creatinine";
};

export const BIOMARKER_DEFINITIONS: BiomarkerDefinition[] = [
  {
    key: "hemoglobin_a1c",
    label: "Hemoglobin A1c",
    units: ["%"],
    patterns: [
      /(?:hemoglobin\s*a1c|hba1c|glycated\s+hemoglobin|glycohemoglobin|hb\s*a1c|glycosylated\s+hemoglobin)/i,
    ],
    exclude: [/(?:interpretation|guideline|target\s+goals|factors\s+that|non\s+diabetic\s+adults|at\s+risk|diagnosing\s+diabetes)/i],
    reference: "< 5.7",
    borderlineHigh: 5.7,
    high: 6.5,
    priority: 100,
    legacyField: "hemoglobin_a1c",
  },
  {
    key: "fasting_glucose",
    label: "Fasting Glucose",
    units: ["mg/dL", "mg/dl", "mmol/L"],
    patterns: [
      /(?:fasting\s+glucose|glucose,?\s*fasting|fasting\s+blood\s+glucose|fasting\s+blood\s+sugar|fbs|sugar\s*\(fasting\)|blood\s+sugar\s*\(fasting\)|glucose\s*\(fasting\)|s\.?\s*glucose\s*\(fasting\)|plasma\s+glucose\s*fasting|fasting\s+plasma\s+glucose)/i,
    ],
    exclude: [/(?:mean\s+blood\s+glucose|post\s*prandial|ppbs|90\s+day\s+average|average\s+blood\s+glucose)/i],
    reference: "70-99",
    low: 70,
    borderlineHigh: 100,
    high: 126,
    priority: 99,
    legacyField: "fasting_glucose",
  },
  {
    key: "total_cholesterol",
    label: "Total Cholesterol",
    units: ["mg/dL", "mg/dl", "mmol/L"],
    patterns: [
      /(?:total\s+cholesterol|cholesterol,?\s*total|serum\s+cholesterol|s\.?\s*cholesterol|cholesterol\s*\(total\)|cholesterol\s*total)/i,
    ],
    exclude: [/(?:hdl|ldl|vldl|chol\/hdl|ldl\/hdl|non-hdl)/i],
    reference: "< 200",
    borderlineHigh: 200,
    high: 240,
    priority: 90,
    legacyField: "total_cholesterol",
  },
  {
    key: "ldl",
    label: "LDL Cholesterol",
    units: ["mg/dL", "mg/dl", "mmol/L"],
    patterns: [
      /(?:direct\s+ldl|ldl(?:\s+cholesterol)?|ldl-c|serum\s+ldl|s\.?\s*ldl|ldl\s*-\s*cholesterol)/i,
    ],
    exclude: [/(?:ldl\/hdl|vldl)/i],
    reference: "< 100",
    borderlineHigh: 100,
    high: 160,
    priority: 95,
    legacyField: "ldl",
  },
  {
    key: "hdl",
    label: "HDL Cholesterol",
    units: ["mg/dL", "mg/dl", "mmol/L"],
    patterns: [
      /(?:direct\s+hdl|hdl(?:\s+cholesterol)?|hdl-c|serum\s+hdl|s\.?\s*hdl|hdl\s*-\s*cholesterol)/i,
    ],
    exclude: [/(?:chol\/hdl|ldl\/hdl|non-hdl|vldl)/i],
    reference: ">= 40",
    low: 40,
    priority: 88,
    legacyField: "hdl",
  },
  {
    key: "triglycerides",
    label: "Triglycerides",
    units: ["mg/dL", "mg/dl", "mmol/L"],
    patterns: [
      /(?:triglycerides?|serum\s+triglycerides|s\.?\s*triglycerides|triglycerides\s*\(serum\)|tg\s+count)/i,
    ],
    reference: "< 150",
    borderlineHigh: 150,
    high: 200,
    priority: 92,
    legacyField: "triglycerides",
  },
  {
    key: "vldl",
    label: "VLDL Cholesterol",
    units: ["mg/dL", "mg/dl", "mmol/L"],
    patterns: [
      /(?:vldl(?:\s+cholesterol)?|vldl-c|serum\s+vldl|s\.?\s*vldl|very\s+low\s+density\s+lipoprotein)/i,
    ],
    reference: "< 30",
    high: 30,
    priority: 86,
  },
  {
    key: "hemoglobin",
    label: "Hemoglobin",
    units: ["g/dL", "g/dl", "g%"],
    patterns: [
      /(?:hemoglobin|haemoglobin|hgb|hb%?|hb\s*count|hemoglobin\s*\(hb\))/i,
    ],
    exclude: [/(?:hba1c|hb\s*a1c|hb\s*a2|foetal\s+hb|fetal\s+hb|mean\s+corpuscular)/i],
    reference: "12-17",
    low: 12,
    high: 17,
    priority: 82,
    legacyField: "hemoglobin",
  },
  {
    key: "wbc",
    label: "White Blood Cells",
    units: ["/cmm", "cumm", "10^3/uL", "/uL", "thousand/cu.mm", "x10^3/uL", "k/uL", "10*3/uL"],
    patterns: [
      /(?:white\s+blood\s+cell(?:\s+count)?|wbc(?:\s+count)?|total\s+leucocyte\s+count|tlc|total\s+leukocyte\s+count|wbc\s+count|total\s+wbc)/i,
    ],
    reference: "4000-11000",
    low: 4000,
    high: 11000,
    priority: 80,
    legacyField: "wbc",
  },
  {
    key: "platelets",
    label: "Platelets",
    units: ["/cmm", "cumm", "10^3/uL", "/uL", "lakhs/cu.mm", "lakh/cumm", "lakhs", "lakh", "x10^3/uL", "10*3/uL"],
    patterns: [
      /(?:platelet(?:s|\s+count)?|plt|platelet\s+count\s*\(plt\)|total\s+platelet\s+count)/i,
    ],
    reference: "150000-450000",
    low: 150000,
    high: 450000,
    priority: 78,
    legacyField: "platelets",
  },
  {
    key: "creatinine",
    label: "Creatinine",
    units: ["mg/dL", "mg/dl", "micromol/L"],
    patterns: [
      /(?:creatinine|serum\s+creatinine|s\.?\s*creatinine|creatinine,?\s*serum|creatinine\s*-\s*serum)/i,
    ],
    reference: "0.6-1.3",
    low: 0.6,
    high: 1.3,
    priority: 84,
    legacyField: "creatinine",
  },
  {
    key: "rbc_count",
    label: "RBC Count",
    units: ["million/cmm", "10^6/uL", "mil/uL", "x10^6/uL"],
    patterns: [/(?:rbc\s+count|total\s+rbc|red\s+blood\s+cell\s+count|\brbc\b)/i],
    exclude: [/(?:distribution\s+width|rdw)/i],
    reference: "4.5-5.5",
    low: 4.5,
    high: 5.5,
    priority: 58,
  },
  {
    key: "hematocrit",
    label: "Hematocrit",
    units: ["%"],
    patterns: [/(?:hematocrit|haematocrit|pcv|packed\s+cell\s+volume)/i],
    reference: "40-49",
    low: 40,
    high: 49,
    priority: 58,
  },
  {
    key: "mcv",
    label: "MCV",
    units: ["fL", "fl"],
    patterns: [/(?:mcv|mean\s+corpuscular\s+volume)/i],
    reference: "83-101",
    low: 83,
    high: 101,
    priority: 54,
  },
  {
    key: "mch",
    label: "MCH",
    units: ["pg"],
    patterns: [/(?:mch|mean\s+corpuscular\s+hemoglobin)/i],
    exclude: [/mchc|mean\s+corpuscular\s+hemoglobin\s+concentration/i],
    reference: "27.1-32.5",
    low: 27.1,
    high: 32.5,
    priority: 50,
  },
  {
    key: "mchc",
    label: "MCHC",
    units: ["g/dL", "g/dl"],
    patterns: [/(?:mchc|mean\s+corpuscular\s+hemoglobin\s+concentration)/i],
    reference: "32.5-36.7",
    low: 32.5,
    high: 36.7,
    priority: 50,
  },
  {
    key: "rdw_cv",
    label: "RDW CV",
    units: ["%"],
    patterns: [/(?:rdw\s*cv|red\s+cell\s+distribution\s+width)/i],
    reference: "11.6-14",
    low: 11.6,
    high: 14,
    priority: 44,
  },
  {
    key: "esr",
    label: "ESR",
    units: ["mm/hr", "mm/1st hr", "mm/hr.", "mm"],
    patterns: [/(?:erythrocyte\s+sedimentation\s+rate|\besr\b)/i],
    exclude: [/(?:clinical\s+notes|increased\s+esr|decreased\s+esr)/i],
    reference: "< 20",
    high: 20,
    priority: 50,
  },
  {
    key: "tsh",
    label: "TSH",
    units: ["microIU/mL", "uIU/mL", "mIU/L", "mlU/L", "uIU/ml", "mIU/ml"],
    patterns: [/(?:thyroid\s+stimulating\s+hormone\s*\(tsh\)|thyroid\s+stimulating\s+hormone|\btsh\b|serum\s+tsh|s\.?\s*tsh)/i],
    exclude: [/(?:circadian\s+variation|diurnal\s+variation|tsh\s+variant|tsh\s+levels\s+are\s+subject)/i],
    reference: "0.35-4.94",
    low: 0.35,
    high: 4.94,
    priority: 72,
  },
  {
    key: "t3",
    label: "Free T3 (FT3)",
    units: ["pg/mL", "pg/ml", "pmol/L"],
    patterns: [/(?:free\s+triiodothyronine(?:\s*\[ft3\])?|\bft3\b|\bft-3\b|triiodothyronine\s*\(t3\))/i],
    reference: "2.0-4.4",
    low: 2.0,
    high: 4.4,
    priority: 70,
  },
  {
    key: "t4",
    label: "Free T4 (FT4)",
    units: ["ng/dL", "ng/dl", "pmol/L"],
    patterns: [/(?:free\s+thyroxine(?:\s*\[ft4\])?|\bft4\b|\bft-4\b|thyroxine\s*\(t4\))/i],
    reference: "0.8-2.0",
    low: 0.8,
    high: 2.0,
    priority: 70,
  },
  {
    key: "iron",
    label: "Iron",
    units: ["μg/dL", "ug/dL", "micro g/dL", "mcg/dL", "umol/L"],
    patterns: [/(?:serum\s+iron|iron,?\s*serum|s\.?\s*iron|\biron\b)/i],
    exclude: [/(?:total\s+iron\s+binding\s+capacity|tibc|technology|dry\s+chemistry)/i],
    reference: "49-181",
    low: 49,
    high: 181,
    priority: 44,
  },
  {
    key: "tibc",
    label: "Total Iron Binding Capacity",
    units: ["μg/dL", "ug/dL", "micro g/dL", "mcg/dL", ""],
    patterns: [/(?:total\s+iron\s+binding\s+capacity|t\s*otal\s+iron\s+binding\s+capacity|\btibc\b)/i],
    exclude: [/(?:technology|microtip)/i],
    reference: "261-462",
    low: 261,
    high: 462,
    priority: 44,
  },
  {
    key: "transferrin_saturation",
    label: "Transferrin Saturation",
    units: ["%"],
    patterns: [/(?:transferrin\s+saturation|iron\s+saturation)/i],
    reference: "20-50",
    low: 20,
    high: 50,
    priority: 40,
  },
  {
    key: "vitamin_d_25_oh",
    label: "25(OH) Vitamin D",
    units: ["ng/mL", "ng/ml", "nmol/L"],
    patterns: [/(?:25\s*-?\s*\(?oh\)?\s*(?:total\s*)?vitamin\s*d|vitamin\s*d\s*\(?25[-\s]*oh\)?|vitamin\s*d3?|25-hydroxy\s*vitamin\s*d|\bvitamin\s*d\b)/i],
    exclude: [/(?:deficiency\s+is\s+defined|insufficiency\s+has\s+been|sufficiency\s+has\s+been|toxicity\s+is\s+observed)/i],
    reference: "30-100",
    low: 30,
    high: 100,
    priority: 76,
  },
  {
    key: "vitamin_b12",
    label: "Vitamin B12",
    units: ["pg/mL", "pg/ml", "pmol/L"],
    patterns: [/(?:vitamin\s*b12|vitamin\s*b-12|vit\s*b12|cyanocobalamin)/i],
    reference: "187-833",
    low: 187,
    high: 833,
    priority: 76,
  },
  {
    key: "urea",
    label: "Urea",
    units: ["mg/dL", "mg/dl"],
    patterns: [/(?:serum\s+urea|s\.?\s*urea|\burea\b)/i],
    exclude: [/(?:blood\s+urea\s+nitrogen|bun)/i],
    reference: "19.3-43",
    low: 19.3,
    high: 43,
    priority: 32,
  },
  {
    key: "blood_urea_nitrogen",
    label: "Blood Urea Nitrogen",
    units: ["mg/dL", "mg/dl"],
    patterns: [/(?:blood\s+urea\s+nitrogen|\bbun\b)/i],
    reference: "9-20",
    low: 9,
    high: 20,
    priority: 32,
  },
  {
    key: "uric_acid",
    label: "Uric Acid",
    units: ["mg/dL", "mg/dl"],
    patterns: [/(?:uric\s+acid|serum\s+uric\s+acid|s\.?\s*uric\s+acid)/i],
    reference: "3.5-8.5",
    low: 3.5,
    high: 8.5,
    priority: 34,
  },
  {
    key: "calcium",
    label: "Calcium",
    units: ["mg/dL", "mg/dl", "mmol/L"],
    patterns: [/(?:serum\s+calcium|s\.?\s*calcium|\bcalcium\b)/i],
    reference: "8.4-10.2",
    low: 8.4,
    high: 10.2,
    priority: 40,
  },
  {
    key: "sgpt",
    label: "SGPT (ALT)",
    units: ["U/L", "u/l", "IU/L"],
    patterns: [/(?:sgpt(?:\s*\(alt\))?|\balt\b|alanine\s+aminotransferase|\bsgpt\b)/i],
    reference: "0-50",
    low: 0,
    high: 50,
    priority: 62,
  },
  {
    key: "sgot",
    label: "SGOT (AST)",
    units: ["U/L", "u/l", "IU/L"],
    patterns: [/(?:sgot(?:\s*\(ast\))?|\bast\b|aspartate\s+aminotransferase|\bsgot\b)/i],
    reference: "17-59",
    low: 17,
    high: 59,
    priority: 58,
  },
  {
    key: "total_bilirubin",
    label: "Total Bilirubin",
    units: ["mg/dL", "mg/dl"],
    patterns: [/(?:total\s+bilirubin|bilirubin,?\s*total|serum\s+bilirubin\s*\(total\))/i],
    reference: "0.2-1.3",
    low: 0.2,
    high: 1.3,
    priority: 34,
  },
  {
    key: "conjugated_bilirubin",
    label: "Conjugated Bilirubin",
    units: ["mg/dL", "mg/dl"],
    patterns: [/(?:conjugated\s+bilirubin|direct\s+bilirubin)/i],
    reference: "0.0-0.3",
    low: 0,
    high: 0.3,
    priority: 28,
  },
  {
    key: "unconjugated_bilirubin",
    label: "Unconjugated Bilirubin",
    units: ["mg/dL", "mg/dl"],
    patterns: [/(?:unconjugated\s+bilirubin|indirect\s+bilirubin)/i],
    reference: "0.0-1.1",
    low: 0,
    high: 1.1,
    priority: 28,
  },
  {
    key: "sodium",
    label: "Sodium",
    units: ["mmol/L", "mEq/L"],
    patterns: [/(?:serum\s+sodium|sodium\s*\(na\+\)|\bsodium\b)/i],
    reference: "136-145",
    low: 136,
    high: 145,
    priority: 64,
  },
  {
    key: "potassium",
    label: "Potassium",
    units: ["mmol/L", "mEq/L"],
    patterns: [/(?:serum\s+potassium|potassium\s*\(k\+\)|\bpotassium\b)/i],
    reference: "3.5-5.1",
    low: 3.5,
    high: 5.1,
    priority: 68,
  },
  {
    key: "chloride",
    label: "Chloride",
    units: ["mmol/L", "mEq/L"],
    patterns: [/(?:serum\s+chloride|chloride\s*\(cl-\)|\bchloride\b)/i],
    reference: "98-107",
    low: 98,
    high: 107,
    priority: 52,
  },
  {
    key: "total_protein",
    label: "Total Protein",
    units: ["g/dL", "g/dl"],
    patterns: [/(?:total\s+protein|protein,?\s*total)/i],
    reference: "6.3-8.2",
    low: 6.3,
    high: 8.2,
    priority: 34,
  },
  {
    key: "albumin",
    label: "Albumin",
    units: ["g/dL", "g/dl"],
    patterns: [/(?:serum\s+albumin|albumin,?\s*serum|\balbumin\b)/i],
    exclude: [/(?:microalbumin)/i],
    reference: "3.5-5.0",
    low: 3.5,
    high: 5.0,
    priority: 36,
  },
  {
    key: "globulin",
    label: "Globulin",
    units: ["g/dL", "g/dl"],
    patterns: [/(?:serum\s+globulin|\bglobulin\b)/i],
    reference: "2.3-3.5",
    low: 2.3,
    high: 3.5,
    priority: 28,
  },
  {
    key: "ag_ratio",
    label: "A/G Ratio",
    units: [""],
    patterns: [/(?:a\/g\s+ratio|albumin[\/\s]*globulin\s+ratio)/i],
    reference: "1.3-1.7",
    low: 1.3,
    high: 1.7,
    priority: 24,
  },
  {
    key: "neutrophils_percent",
    label: "Neutrophils %",
    units: ["%"],
    patterns: [/(?:neutrophils?|polymorphs?)/i],
    exclude: [/(?:absolute\s+neutrophil)/i],
    reference: "40-75",
    low: 40,
    high: 75,
    priority: 40,
  },
  {
    key: "lymphocytes_percent",
    label: "Lymphocytes %",
    units: ["%"],
    patterns: [/(?:lymphocytes?)/i],
    exclude: [/(?:absolute\s+lymphocyte)/i],
    reference: "20-45",
    low: 20,
    high: 45,
    priority: 40,
  },
  {
    key: "eosinophils_percent",
    label: "Eosinophils %",
    units: ["%"],
    patterns: [/(?:eosinophils?)/i],
    exclude: [/(?:absolute\s+eosinophil)/i],
    reference: "1-6",
    low: 1,
    high: 6,
    priority: 36,
  },
  {
    key: "monocytes_percent",
    label: "Monocytes %",
    units: ["%"],
    patterns: [/(?:monocytes?)/i],
    exclude: [/(?:absolute\s+monocyte)/i],
    reference: "2-10",
    low: 2,
    high: 10,
    priority: 36,
  },
  {
    key: "basophils_percent",
    label: "Basophils %",
    units: ["%"],
    patterns: [/(?:basophils?)/i],
    exclude: [/(?:absolute\s+basophil)/i],
    reference: "0-2",
    low: 0,
    high: 2,
    priority: 32,
  },
  {
    key: "psa_total",
    label: "PSA Total",
    units: ["ng/mL", "ng/dl"],
    patterns: [/(?:psa[-\s]*prostate\s+specific\s+antigen,\s*total|\bpsa\b)/i],
    reference: "0-4",
    low: 0,
    high: 4,
    priority: 46,
  },
];

export const BIOMARKER_DEFINITION_MAP = new Map(
  BIOMARKER_DEFINITIONS.map((definition) => [definition.key, definition]),
);

export function getBiomarkerDefinition(key: string): BiomarkerDefinition | undefined {
  if (!key) return undefined;
  const direct = BIOMARKER_DEFINITION_MAP.get(key);
  if (direct) return direct;

  const normalized = key.toLowerCase().replace(/[\s_-]+/g, "");
  for (const def of BIOMARKER_DEFINITIONS) {
    if (def.key.replace(/[\s_-]+/g, "") === normalized) return def;
    if (def.patterns.some((p) => p.test(key))) return def;
  }
  return undefined;
}
